### ISSUE TITLE
I'm getting an error when doing an ibc transfer in keplr.

### ISSUE THREAD

**Issue by tomas-dora** [cosmos/ibc-go#4792]
cosmos-sdk: `v0.47.3`
ibc-go: `v7.1.0`

this is my ibc transfer log in `keplr`.

```json
{
    "tx_response":{
        "height":"0",
        "txhash":"52269A178C3F356DAEC53F2A9A4A62E8E745C008D939F6EAB8FB4EDEDEA5DD8E",
        "codespace":"undefined",
        "code":111222,
        "data":"",
        "raw_log":"recovered: expected *legacytx.LegacyMsg when using amino JSON\nstack:\ngoroutine 2497466 [running]:\nruntime/debug.Stack()\n\t/usr/local/go/src/runtime/debug/stack.go:24 +0x65\ngithub.com/cosmos/cosmos-sdk/baseapp.newDefaultRecoveryMiddleware.func1({0x226b660, 0xc02c0f4530})\n\t/home/ubuntu/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.47.3/baseapp/recovery.go:71 +0x27\ngithub.com/cosmos/cosmos-sdk/baseapp.newRecoveryMiddleware.func1({0x226b660?, 0xc02c0f4530?})\n\t/home/ubuntu/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.47.3/baseapp/recovery.go:39 +0x30\ngithub.com/cosmos/cosmos-sdk/baseapp.processRecovery({0x226b660, 0xc02c0f4530}, 0xc006363080?)\n\t/home/ubuntu/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.47.3/baseapp/recovery.go:28 +0x37\ngithub.com/cosmos/cosmos-sdk/baseapp.processRecovery({0x226b660, 0xc02c0f4530}, 0x33e5240?)\n\t/home/ubuntu/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.47.3/baseapp/recovery.go:33 +0x5e\ngithub.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).runTx.func1()\n\t/home/ubuntu/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.47.3/baseapp/baseapp.go:641 +0xf0\npanic({0x226b660, 0xc02c0f4530})\n\t/usr/local/go/src/runtime/panic.go:890 +0x263\ngithub.com/cosmos/cosmos-sdk/x/auth/ante.SetUpContextDecorator.AnteHandle.func1()\n\t/home/ubuntu/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.47.3/x/auth/ante/setup.go:57 +0x1e6\npanic({0x226b660, 0xc02c0f4530})\n\t/usr/local/go/src/runtime/panic.go:884 +0x213\ngithub.com/cosmos/cosmos-sdk/x/auth/migrations/legacytx.StdSignBytes({0xc03c17cdc0, 0x8}, 0x23, 0x5, 0x0, {{0xc0229eb188, 0x1, 0x1}, 0x1be68, {0x0, ...}, ...}, ...)\n\t/home/ubuntu/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.47.3/x/auth/migrations/legacytx/stdsign.go:60 +0x445\ngithub.com/cosmos/cosmos-sdk/x/auth/tx.signModeLegacyAminoJSONHandler.GetSignBytes({}, 0x4122e8?, {{0xc01d133740, 0x2b}, {0xc03c17cdc0, 0x8}, 0x23, 0x5, {0x33df030, 0xc0229eb458}}, ...)\n\t/home/ubuntu/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.47.3/x/auth/tx/legacy_amino_json.go:68 +0x40c\ngithub.com/cosmos/cosmos-sdk/x/auth/signing.SignModeHandlerMap.GetSignBytes({0x1, {0xc000056800, 0x3, 0x4}, 0xc000eaba70}, 0x407cb4?, {{0xc01d133740, 0x2b}, {0xc03c17cdc0, 0x8}, ...}, ...)\n\t/home/ubuntu/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.47.3/x/auth/signing/handler_map.go:59 +0xbe\ngithub.com/cosmos/cosmos-sdk/x/auth/signing.VerifySignature({0x33df030?, 0xc0229eb458}, {{0xc01d133740, 0x2b}, {0xc03c17cdc0, 0x8}, 0x23, 0x5, {0x33df030, 0xc0229eb458}}, ...)\n\t/home/ubuntu/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.47.3/x/auth/signing/verify.go:17 +0xdb\ngithub.com/cosmos/cosmos-sdk/x/auth/ante.SigVerificationDecorator.AnteHandle({{_, _}, {_, _}}, {{0x33d1ea8, 0xc035e2c660}, {0x33e5240, 0xc04732d3c0}, {{0xb, 0x0}, ...}, ...}, ...)\n\t/home/ubuntu/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.47.3/x/auth/ante/sigverify.go:292 +0x65a\ngithub.com/cosmos/cosmos-sdk/types.ChainAnteDecorators.func1({{0x33d1ea8, 0xc035e2c660}, {0x33e5240, 0xc04732d3c0}, {{0xb, 0x0}, {0xc03c17cdc0, 0x8}, 0x76cf6, {0x1b7d69e4, ...}, ...}, ...}, ...)\n\t/home/ubuntu/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.47.3/types/handler.go:49 +0x136\ngithub.com/cosmos/cosmos-sdk/x/auth/ante.SigGasConsumeDecorator.AnteHandle({{_, _}, _}, {{0x33d1ea8, 0xc035e2c660}, {0x33e5240, 0xc04732d3c0}, {{0xb, 0x0}, {0xc03c17cdc0, ...}, ...}, ...}, ...)\n\t/home/ubuntu/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.47.3/x/auth/ante/sigverify.go:194 +0x577\ngithub.com/cosmos/cosmos-sdk/types.ChainAnteDecorators.func1({{0x33d1ea8, 0xc035e2c660}, {0x33e5240, 0xc04732d3c0}, {{0xb, 0x0}, {0xc03c17cdc0, 0x8}, 0x76cf6, {0x1b7d69e4, ...}, ...}, ...}, ...)\n\t/home/ubuntu/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.47.3/types/handler.go:49 +0x136\ngithub.com/cosmos/cosmos-sdk/x/auth/ante.ValidateSigCountDecorator.AnteHandle({{_, _}}, {{0x33d1ea8, 0xc035e2c660}, {0x33e5240, 0xc04732d3c0}, {{0xb, 0x0}, {0xc03c17cdc0, 0x8}, ...}, ...}, ...)\n\t/home/ubuntu/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.47.3/x/auth/ante/sigverify.go:384 +0x3f7\ngithub.com/cosmos/cosmos-sdk/types.ChainAnteDecorators.func1({{0x33d1ea8, 0xc035e2c660}, {0x33e5240, 0xc04732d3c0}, {{0xb, 0x0}, {0xc03c17cdc0, 0x8}, 0x76cf6, {0x1b7d69e4, ...}, ...}, ...}, ...)\n\t/home/ubuntu/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.47.3/types/handler.go:49 +0x136\ngithub.com/cosmos/cosmos-sdk/x/auth/ante.SetPubKeyDecorator.AnteHandle({{_, _}}, {{0x33d1ea8, 0xc035e2c660}, {0x33e5240, 0xc04732d3c0}, {{0xb, 0x0}, {0xc03c17cdc0, 0x8}, ...}, ...}, ...)\n\t/home/ubuntu/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.47.3/x/auth/ante/sigverify.go:126 +0xad7\ngithub.com/cosmos/cosmos-sdk/types.ChainAnteDecorators.func1({{0x33d1ea8, 0xc035e2c660}, {0x33e5240, 0xc04732d3c0}, {{0xb, 0x0}, {0xc03c17cdc0, 0x8}, 0x76cf6, {0x1b7d69e4, ...}, ...}, ...}, ...)\n\t/home/ubuntu/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.47.3/types/handler.go:49 +0x136\ngithub.com/cosmos/cosmos-sdk/x/auth/ante.DeductFeeDecorator.AnteHandle({{_, _}, {_, _}, {_, _}, _}, {{0x33d1ea8, 0xc035e2c660}, {0x33e5240, ...}, ...}, ...)\n\t/home/ubuntu/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.47.3/x/auth/ante/fee.go:67 +0x337\ngithub.com/cosmos/cosmos-sdk/types.ChainAnteDecorators.func1({{0x33d1ea8, 0xc035e2c660}, {0x33e5240, 0xc04732d3c0}, {{0xb, 0x0}, {0xc03c17cdc0, 0x8}, 0x76cf6, {0x1b7d69e4, ...}, ...}, ...}, ...)\n\t/home/ubuntu/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.47.3/types/handler.go:49 +0x136\ngithub.com/cosmos/cosmos-sdk/x/auth/ante.ConsumeTxSizeGasDecorator.AnteHandle({{_, _}}, {{0x33d1ea8, 0xc035e2c660}, {0x33e5240, 0xc04732d3c0}, {{0xb, 0x0}, {0xc03c17cdc0, 0x8}, ...}, ...}, ...)\n\t/home/ubuntu/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.47.3/x/auth/ante/basic.go:143 +0x5c6\ngithub.com/cosmos/cosmos-sdk/types.ChainAnteDecorators.func1({{0x33d1ea8, 0xc035e2c660}, {0x33e5240, 0xc04732d3c0}, {{0xb, 0x0}, {0xc03c17cdc0, 0x8}, 0x76cf6, {0x1b7d69e4, ...}, ...}, ...}, ...)\n\t/home/ubuntu/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.47.3/types/handler.go:49 +0x136\ngithub.com/cosmos/cosmos-sdk/x/auth/ante.ValidateMemoDecorator.AnteHandle({{_, _}}, {{0x33d1ea8, 0xc035e2c660}, {0x33e5240, 0xc04732d3c0}, {{0xb, 0x0}, {0xc03c17cdc0, 0x8}, ...}, ...}, ...)\n\t/home/ubuntu/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.47.3/x/auth/ante/basic.go:67 +0x1d7\ngithub.com/cosmos/cosmos-sdk/types.ChainAnteDecorators.func1({{0x33d1ea8, 0xc035e2c660}, {0x33e5240, 0xc04732d3c0}, {{0xb, 0x0}, {0xc03c17cdc0, 0x8}, 0x76cf6, {0x1b7d69e4, ...}, ...}, ...}, ...)\n\t/home/ubuntu/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.47.3/types/handler.go:49 +0x136\ngithub.com/cosmos/cosmos-sdk/x/auth/ante.TxTimeoutHeightDecorator.AnteHandle({}, {{0x33d1ea8, 0xc035e2c660}, {0x33e5240, 0xc04732d3c0}, {{0xb, 0x0}, {0xc03c17cdc0, 0x8}, 0x76cf6, ...}, ...}, ...)\n\t/home/ubuntu/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.47.3/x/auth/ante/basic.go:206 +0x297\ngithub.com/cosmos/cosmos-sdk/types.ChainAnteDecorators.func1({{0x33d1ea8, 0xc035e2c660}, {0x33e5240, 0xc04732d3c0}, {{0xb, 0x0}, {0xc03c17cdc0, 0x8}, 0x76cf6, {0x1b7d69e4, ...}, ...}, ...}, ...)\n\t/home/ubuntu/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.47.3/types/handler.go:49 +0x136\ngithub.com/cosmos/cosmos-sdk/x/auth/ante.ValidateBasicDecorator.AnteHandle({}, {{0x33d1ea8, 0xc035e2c660}, {0x33e5240, 0xc04732d3c0}, {{0xb, 0x0}, {0xc03c17cdc0, 0x8}, 0x76cf6, ...}, ...}, ...)\n\t/home/ubuntu/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.47.3/x/auth/ante/basic.go:34 +0x157\ngithub.com/cosmos/cosmos-sdk/types.ChainAnteDecorators.func1({{0x33d1ea8, 0xc035e2c660}, {0x33e5240, 0xc04732d3c0}, {{0xb, 0x0}, {0xc03c17cdc0, 0x8}, 0x76cf6, {0x1b7d69e4, ...}, ...}, ...}, ...)\n\t/home/ubuntu/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.47.3/types/handler.go:49 +0x136\ngithub.com/cosmos/cosmos-sdk/x/auth/ante.RejectExtensionOptionsDecorator.AnteHandle({_}, {{0x33d1ea8, 0xc035e2c660}, {0x33e5240, 0xc04732d3c0}, {{0xb, 0x0}, {0xc03c17cdc0, 0x8}, 0x76cf6, ...}, ...}, ...)\n\t/home/ubuntu/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.47.3/x/auth/ante/ext.go:52 +0x137\ngithub.com/cosmos/cosmos-sdk/types.ChainAnteDecorators.func1({{0x33d1ea8, 0xc035e2c660}, {0x33e5240, 0xc04732d3c0}, {{0xb, 0x0}, {0xc03c17cdc0, 0x8}, 0x76cf6, {0x1b7d69e4, ...}, ...}, ...}, ...)\n\t/home/ubuntu/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.47.3/types/handler.go:49 +0x136\ngithub.com/CosmWasm/wasmd/x/wasm/keeper.CountTXDecorator.AnteHandle({{_, _}}, {{0x33d1e38, 0xc0002e0070}, {0x33e5240, 0xc04732d3c0}, {{0xb, 0x0}, {0xc03c17cdc0, 0x8}, ...}, ...}, ...)\n\t/home/ubuntu/go/pkg/mod/github.com/!cosm!wasm/wasmd@v0.40.2/x/wasm/keeper/ante.go:45 +0x33c\ngithub.com/cosmos/cosmos-sdk/types.ChainAnteDecorators.func1({{0x33d1e38, 0xc0002e0070}, {0x33e5240, 0xc04732d3c0}, {{0xb, 0x0}, {0xc03c17cdc0, 0x8}, 0x76cf6, {0x1b7d69e4, ...}, ...}, ...}, ...)\n\t/home/ubuntu/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.47.3/types/handler.go:49 +0x136\ngithub.com/CosmWasm/wasmd/x/wasm/keeper.LimitSimulationGasDecorator.AnteHandle({_}, {{0x33d1e38, 0xc0002e0070}, {0x33e5240, 0xc04732d3c0}, {{0xb, 0x0}, {0xc03c17cdc0, 0x8}, 0x76cf6, ...}, ...}, ...)\n\t/home/ubuntu/go/pkg/mod/github.com/!cosm!wasm/wasmd@v0.40.2/x/wasm/keeper/ante.go:84 +0x4e8\ngithub.com/cosmos/cosmos-sdk/types.ChainAnteDecorators.func1({{0x33d1e38, 0xc0002e0070}, {0x33e5240, 0xc04732d3c0}, {{0xb, 0x0}, {0xc03c17cdc0, 0x8}, 0x76cf6, {0x1b7d69e4, ...}, ...}, ...}, ...)\n\t/home/ubuntu/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.47.3/types/handler.go:49 +0x136\ngithub.com/cosmos/cosmos-sdk/x/auth/ante.SetUpContextDecorator.AnteHandle({}, {{0x33d1e38, 0xc0002e0070}, {0x33e5240, 0xc04732d3c0}, {{0xb, 0x0}, {0xc03c17cdc0, 0x8}, 0x76cf6, ...}, ...}, ...)\n\t/home/ubuntu/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.47.3/x/auth/ante/setup.go:62 +0x593\ngithub.com/cosmos/cosmos-sdk/types.ChainAnteDecorators.func1({{0x33d1e38, 0xc0002e0070}, {0x33e5240, 0xc04732d3c0}, {{0xb, 0x0}, {0xc03c17cdc0, 0x8}, 0x76cf6, {0x1b7d69e4, ...}, ...}, ...}, ...)\n\t/home/ubuntu/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.47.3/types/handler.go:49 +0x136\ngithub.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).runTx(0xc000ea2b40, 0x0, {0xc00135b380, 0x182, 0x183})\n\t/home/ubuntu/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.47.3/baseapp/baseapp.go:696 +0x566\ngithub.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).CheckTx(0xc000ea2b40, {{0xc00135b380?, 0x22732d3d8d630e51?, 0xa4506ceb90befffa?}, 0xbef9a3f7?})\n\t/home/ubuntu/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.47.3/baseapp/abci.go:370 +0x86\ngithub.com/cometbft/cometbft/abci/client.(*localClient).CheckTxAsync(0xc000b4ca20, {{0xc00135b380?, 0x8edda5dede4efbb8?, 0xc0376977d0?}, 0x135b380?})\n\t/home/ubuntu/go/pkg/mod/github.com/cometbft/cometbft@v0.37.1/abci/client/local_client.go:93 +0x118\ngithub.com/cometbft/cometbft/proxy.(*appConnMempool).CheckTxAsync(0xc00d0f51a0, {{0xc00135b380?, 0xffffffff?, 0x0?}, 0x638bc98?})\n\t/home/ubuntu/go/pkg/mod/github.com/cometbft/cometbft@v0.37.1/proxy/app_conn.go:154 +0x108\ngithub.com/cometbft/cometbft/mempool/v0.(*CListMempool).CheckTx(0xc000b332c0, {0xc00135b380, 0x182, 0x183}, 0x180?, {0xb0e0?, {0x0?, 0xc00638bff0?}})\n\t/home/ubuntu/go/pkg/mod/github.com/cometbft/cometbft@v0.37.1/mempool/v0/clist_mempool.go:254 +0x30d\ngithub.com/cometbft/cometbft/rpc/core.BroadcastTxSync(0xc00f19aa20, {0xc00135b380, 0x182, 0x183})\n\t/home/ubuntu/go/pkg/mod/github.com/cometbft/cometbft@v0.37.1/rpc/core/mempool.go:35 +0xf6\ngithub.com/cometbft/cometbft/rpc/client/local.(*Local).BroadcastTxSync(0xc01ceb5440?, {0x0?, 0x0?}, {0xc00135b380?, 0x100000000?, 0x35f66d8?})\n\t/home/ubuntu/go/pkg/mod/github.com/cometbft/cometbft@v0.37.1/rpc/client/local/local.go:99 +0x2b\ngithub.com/cosmos/cosmos-sdk/client.Context.BroadcastTxSync({{0x0, 0x0, 0x0}, {0x33e6900, 0xc00f19aa00}, 0xc000eb6e00, {0xc001732740, 0x8}, {0x33f0bc0, 0xc00007fca0}, ...}, ...)\n\t/home/ubuntu/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.47.3/client/broadcast.go:89 +0x12e\ngithub.com/cosmos/cosmos-sdk/client.Context.BroadcastTx({{0x0, 0x0, 0x0}, {0x33e6900, 0xc00f19aa00}, 0xc000eb6e00, {0xc001732740, 0x8}, {0x33f0bc0, 0xc00007fca0}, ...}, ...)\n\t/home/ubuntu/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.47.3/client/broadcast.go:26 +0x78\ngithub.com/cosmos/cosmos-sdk/client.TxServiceBroadcast({_, _}, {{0x0, 0x0, 0x0}, {0x33e6900, 0xc00f19aa00}, 0xc000eb6e00, {0xc001732740, 0x8}, ...}, ...)\n\t/home/ubuntu/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.47.3/client/broadcast.go:121 +0x105\ngithub.com/cosmos/cosmos-sdk/client.Context.Invoke({{0x0, 0x0, 0x0}, {0x33e6900, 0xc00f19aa00}, 0xc000eb6e00, {0xc001732740, 0x8}, {0x33f0bc0, 0xc00007fca0}, ...}, ...)\n\t/home/ubuntu/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.47.3/client/grpc_query.go:52 +0x1e5\ngithub.com/cosmos/cosmos-sdk/types/tx.(*serviceClient).BroadcastTx(0xc0019e6cc0, {0x33d1ea8, 0xc037697620}, 0x22c1c60?, {0xc010df91a0, 0x2, 0x2})\n\t/home/ubuntu/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.47.3/types/tx/service.pb.go:1281 +0xce\ngithub.com/cosmos/cosmos-sdk/types/tx.request_Service_BroadcastTx_0({0x33d1ea8, 0xc037697620}, {0x33d6080, 0xc003ccfb90}, {0x33e1e80, 0xc0019e6cc0}, 0xc00635f200, 0x22a30c0?)\n\t/home/ubuntu/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.47.3/types/tx/service.pb.gw.go:136 +0x283\ngithub.com/cosmos/cosmos-sdk/types/tx.RegisterServiceHandlerClient.func3({0x33bd6b0, 0xc0229eb038}, 0xc00635f200, 0xc0003ce8c0?)\n\t/home/ubuntu/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.47.3/types/tx/service.pb.gw.go:705 +0x165\ngithub.com/grpc-ecosystem/grpc-gateway/runtime.(*ServeMux).ServeHTTP(0xc008cb4380, {0x33bd6b0, 0xc0229eb038}, 0xc00635f200)\n\t/home/ubuntu/go/pkg/mod/github.com/grpc-ecosystem/grpc-gateway@v1.16.0/runtime/mux.go:240 +0x856\ngithub.com/gorilla/mux.(*Router).ServeHTTP(0xc000c229c0, {0x33bd6b0, 0xc0229eb038}, 0xc00635f000)\n\t/home/ubuntu/go/pkg/mod/github.com/gorilla/mux@v1.8.0/mux.go:210 +0x1cf\ngithub.com/gorilla/handlers.(*cors).ServeHTTP(0xc00f1d9440, {0x33bd6b0, 0xc0229eb038}, 0xc00635f000)\n\t/home/ubuntu/go/pkg/mod/github.com/gorilla/handlers@v1.5.1/cors.go:138 +0x6c2\ngithub.com/cometbft/cometbft/rpc/jsonrpc/server.maxBytesHandler.ServeHTTP({{0x33ae2e0?, 0xc00f1d9440?}, 0x4126c7?}, {0x33bd6b0?, 0xc0229eb038}, 0xc00635f000)\n\t/home/ubuntu/go/pkg/mod/github.com/cometbft/cometbft@v0.37.1/rpc/jsonrpc/server/http_server.go:256 +0x124\ngithub.com/cometbft/cometbft/rpc/jsonrpc/server.RecoverAndLogHandler.func1({0x33cec30?, 0xc0001f0700}, 0xc00635f000)\n\t/home/ubuntu/go/pkg/mod/github.com/cometbft/cometbft@v0.37.1/rpc/jsonrpc/server/http_server.go:229 +0x37f\nnet/http.HandlerFunc.ServeHTTP(0x0?, {0x33cec30?, 0xc0001f0700?}, 0x97d514?)\n\t/usr/local/go/src/net/http/server.go:2122 +0x2f\nnet/http.serverHandler.ServeHTTP({0x33b76c0?}, {0x33cec30, 0xc0001f0700}, 0xc00635f000)\n\t/usr/local/go/src/net/http/server.go:2936 +0x316\nnet/http.(*conn).serve(0xc00571d170, {0x33d1ea8, 0xc00b4005d0})\n\t/usr/local/go/src/net/http/server.go:1995 +0x612\ncreated by net/http.(*Server).Serve\n\t/usr/local/go/src/net/http/server.go:3089 +0x5ed\n: panic",
        "logs":[

        ],
        "info":"",
        "gas_wanted":"0",
        "gas_used":"0",
        "tx":null,
        "timestamp":"",
        "events":[

        ]
    }
}
```

**Comment by damiannolan** [comment]
Hi @tomas-dora. This was patched in https://github.com/cosmos/ibc-go/pull/3907 and released in `v7.2.0` . I would recommend a software upgrade.

I will close this issue. Thank you for reaching out!
