### ISSUE TITLE
Panic with NewMsgServerImpl (27-interchain-accounts/host/keeper/msg_server.go)

### ISSUE THREAD

**Issue by RaulBernal** [cosmos/ibc-go#6415]
## Summary of Bug
Upgrading from Cosmos v0.47.11 to v0.50.6 using IBC/go 8.2.0 I have no problem.
If I use IBC/go 8.3.1 I get a panic before start the upgrade process.
```go
build/bcnad start 
panic: query router must not be nil

goroutine 1 [running]:
github.com/cosmos/ibc-go/v8/modules/apps/27-interchain-accounts/host/keeper.NewMsgServerImpl(...)
	/home/raul/go/pkg/mod/github.com/cosmos/ibc-go/v8@v8.3.1/modules/apps/27-interchain-accounts/host/keeper/msg_server.go:28
github.com/cosmos/ibc-go/v8/modules/apps/27-interchain-accounts.AppModule.RegisterServices({{}, 0xc00098d990?, 0xc00098da20?}, {0x408f2e0, 0xc0009d9680})
	/home/raul/go/pkg/mod/github.com/cosmos/ibc-go/v8@v8.3.1/modules/apps/27-interchain-accounts/module.go:153 +0x32a
github.com/cosmos/cosmos-sdk/runtime.(*App).RegisterModules(0xc0011ea580, {0xc000b8b810?, 0x4?, 0x40a3468?})
	/home/raul/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.50.6/runtime/app.go:80 +0x267
github.com/BitCannaGlobal/bcna/app.(*App).registerIBCModules(0xc00098d008, {0x4052f00, 0xc0015fc1c0})
	/home/raul/bcnav4wasm/app/ibc.go:179 +0x30d2
github.com/BitCannaGlobal/bcna/app.New({0x4094350, 0xc0009fd490}, {0x40a9140, 0xc000186408}, {0x0, 0x0}, 0x1, {0x4052f00, 0xc0015fc1c0}, {0xc000b21ce0, ...})
	/home/raul/bcnav4wasm/app/app.go:327 +0x77f
github.com/BitCannaGlobal/bcna/cmd/bcnad/cmd.newApp({0x4094350, 0xc0009fd490}, {0x40a9140, 0xc000186408}, {0x0, 0x0}, {0x4052f00, 0xc0015fc1c0})
	/home/raul/bcnav4wasm/cmd/bcnad/cmd/commands.go:135 +0xaa
github.com/cosmos/cosmos-sdk/server.startApp(0xc00158af40, 0x39c5870, {0x39c5fe8, 0x0, 0x0, 0x0, 0x39c5ff8})
	/home/raul/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.50.6/server/start.go:618 +0x223
github.com/cosmos/cosmos-sdk/server.start(_, {{0x0, 0x0, 0x0}, {0x40afc70, 0xc0015b3ce0}, 0x0, {0xc000ff4870, 0xe}, {0x40ce520, ...}, ...}, ...)
	/home/raul/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.50.6/server/start.go:224 +0x159
github.com/cosmos/cosmos-sdk/server.StartCmdWithOptions.func2.1()
	/home/raul/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.50.6/server/start.go:198 +0x63
github.com/cosmos/cosmos-sdk/server.wrapCPUProfile(0xc00158af40, 0xc00130f9f8)
	/home/raul/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.50.6/server/start.go:570 +0x1b3
github.com/cosmos/cosmos-sdk/server.StartCmdWithOptions.func2(0xc0011fec08, {0x5dc8c60?, 0x0?, 0x0?})
	/home/raul/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.50.6/server/start.go:197 +0x212
github.com/spf13/cobra.(*Command).execute(0xc0011fec08, {0x5dc8c60, 0x0, 0x0})
	/home/raul/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:983 +0xaca
github.com/spf13/cobra.(*Command).ExecuteC(0xc000c7fb08)
	/home/raul/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:1115 +0x3ff
github.com/spf13/cobra.(*Command).Execute(...)
	/home/raul/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:1039
github.com/spf13/cobra.(*Command).ExecuteContext(...)
	/home/raul/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:1032
github.com/cosmos/cosmos-sdk/server/cmd.Execute(0xc000c7fb08, {0x0, 0x0}, {0xc0011bfcc0, 0x10})
	/home/raul/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.50.6/server/cmd/execute.go:34 +0x187
main.main()
	/home/raul/bcnav4wasm/cmd/bcnad/main.go:15 +0x33
```

If I comment the function `NewMsgServerImpl` it works
```go
func NewMsgServerImpl(keeper *Keeper) types.MsgServer {
//      if keeper.queryRouter == nil {
//              panic("query router must not be nil")
//      }
        return &msgServer{Keeper: keeper}
}
```

## Expected Behaviour
The expected behaviour is to perform the software upgrade and continue.
This is the output when I comment the previous function:
```go
build/bcnad start
10:57AM INF Upgrading IAVL storage for faster queries + execution on live state. This may take a while commit=436F6D6D697449447B5B5D3A307D module=server store_key="KVStoreKey{0xc000b72da0, circuit}" version=420
10:57AM INF Upgrading IAVL storage for faster queries + execution on live state. This may take a while commit=436F6D6D697449447B5B5D3A307D module=server store_key="KVStoreKey{0xc0018c0fb0, feeibc}" version=420
10:57AM INF Upgrading IAVL storage for faster queries + execution on live state. This may take a while commit=436F6D6D697449447B5B5D3A307D module=server store_key="KVStoreKey{0xc0006901c0, nft}" version=420
10:57AM INF Upgrading IAVL storage for faster queries + execution on live state. This may take a while commit=436F6D6D697449447B5B5D3A307D module=server store_key="KVStoreKey{0xc002d5df00, wasm}" version=420
10:57AM INF starting node with ABCI CometBFT in-process module=server
10:57AM INF service start impl=multiAppConn module=proxy msg="Starting multiAppConn service"
10:57AM INF service start connection=query impl=localClient module=abci-client msg="Starting localClient service"
10:57AM INF service start connection=snapshot impl=localClient module=abci-client msg="Starting localClient service"
10:57AM INF service start connection=mempool impl=localClient module=abci-client msg="Starting localClient service"
10:57AM INF service start connection=consensus impl=localClient module=abci-client msg="Starting localClient service"
10:57AM INF service start impl=EventBus module=events msg="Starting EventBus service"
10:57AM INF service start impl=PubSub module=pubsub msg="Starting PubSub service"
10:57AM INF service start impl=IndexerService module=txindex msg="Starting IndexerService service"
10:57AM INF Found local state with non-zero height, skipping state sync module=server
10:57AM INF ABCI Handshake App Info hash=94D4C22DB8853813BF0534CE4A548A86FDB036AE5336B0275CD3A76C75C3856C height=419 module=consensus protocol-version=0 software-version=stickyfingers-upgrade-8e41de9b608864e9fefc999985d743d23e5993c4
10:57AM INF ABCI Replay Blocks appHeight=419 module=consensus stateHeight=419 storeHeight=420
10:57AM INF Replay last block using real app module=consensus
10:57AM INF applying upgrade "stickyfingers" at height: 420 module=x/upgrade
10:57AM INF Cosmos-SDK v0.50.x is here... module=server
10:57AM INF Module: gov, Version: 4 module=server
10:57AM INF Module: mint, Version: 2 module=server
10:57AM INF Module: transfer, Version: 3 module=server
10:57AM INF Module: auth, Version: 4 module=server
10:57AM INF Module: capability, Version: 1 module=server
10:57AM INF Module: feegrant, Version: 2 module=server
10:57AM INF Module: genutil, Version: 1 module=server
10:57AM INF Module: params, Version: 1 module=server
10:57AM INF Module: vesting, Version: 1 module=server
10:57AM INF Module: ibc, Version: 4 module=server
10:57AM INF Module: staking, Version: 4 module=server
10:57AM INF Module: authz, Version: 2 module=server
10:57AM INF Module: bcna, Version: 1 module=server
10:57AM INF Module: crisis, Version: 2 module=server
10:57AM INF Module: distribution, Version: 3 module=server
10:57AM INF Module: evidence, Version: 1 module=server
10:57AM INF Module: group, Version: 2 module=server
10:57AM INF Module: upgrade, Version: 2 module=server
10:57AM INF Module: bank, Version: 4 module=server
10:57AM INF Module: burn, Version: 1 module=server
10:57AM INF Module: consensus, Version: 1 module=server
10:57AM INF Module: interchainaccounts, Version: 2 module=server
10:57AM INF Module: slashing, Version: 3 module=server
10:57AM INF adding a new module: 06-solomachine module=server
10:57AM INF adding a new module: 07-tendermint module=server
10:57AM INF adding a new module: circuit module=server
10:57AM INF adding a new module: feeibc module=server
10:57AM INF migrating module gov from version 4 to version 5 module=server
10:57AM INF migrating module ibc from version 4 to version 5 module=server
10:57AM INF successfully migrated client to self-manage params module=x/ibc/client
10:57AM INF successfully migrated connection to self-manage params module=x/ibc/connection
10:57AM INF migrating module ibc from version 5 to version 6 module=server
10:57AM INF successfully migrated ibc channel params module=x/ibc/channel
10:57AM INF migrating module interchainaccounts from version 2 to version 3 module=server
10:57AM INF successfully migrated ica/host submodule to self-manage params module=x/ibc-interchainaccounts
10:57AM INF successfully migrated ica/controller submodule to self-manage params module=x/ibc-interchainaccounts
10:57AM INF adding a new module: nft module=server
10:57AM INF adding a new module: runtime module=server
10:57AM INF migrating module slashing from version 3 to version 4 module=server
10:57AM INF migrating module staking from version 4 to version 5 module=server
10:57AM INF migrating module transfer from version 3 to version 4 module=server
10:57AM INF successfully migrated transfer app self-manage params module=x/ibc-transfer
10:57AM INF migrating module transfer from version 4 to version 5 module=server
10:57AM INF successfully added metadata to IBC voucher denominations module=x/ibc-transfer
10:57AM INF adding a new module: wasm module=server
10:57AM INF migrating module auth from version 4 to version 5 module=server
10:57AM INF post migrate version map: map[06-solomachine:0 07-tendermint:0 auth:5 authz:2 bank:4 capability:1 circuit:1 consensus:1 crisis:2 distribution:3 evidence:1 feegrant:2 feeibc:2 genutil:1 gov:5 group:2 ibc:6 interchainaccounts:3 mint:2 nft:1 params:1 runtime:0 slashing:4 staking:5 transfer:5 upgrade:2 vesting:1 wasm:4] module=server
10:57AM INF finalized block block_app_hash=2EDD9600B9911D18502CAF25E1DEED4F98E352C447B86A24D670CB7107B51B25 height=420 module=consensus num_txs_res=0 num_val_updates=0
10:57AM INF executed block app_hash=2EDD9600B9911D18502CAF25E1DEED4F98E352C447B86A24D670CB7107B51B25 height=420 module=consensus
10:57AM INF committed state block_app_hash=94D4C22DB8853813BF0534CE4A548A86FDB036AE5336B0275CD3A76C75C3856C height=420 module=consensus
10:57AM INF Completed ABCI Handshake - CometBFT and App are synced appHash=2EDD9600B9911D18502CAF25E1DEED4F98E352C447B86A24D670CB7107B51B25 appHeight=419 module=consensus
10:57AM INF Version info abci=2.0.0 block=11 commit_hash= module=server p2p=8 tendermint_version=0.38.7
```

## Steps to Reproduce
Here is the source code with last commits:
https://github.com/RaulBernal/bcnav4wasm/commits/stickyfingers-upgrade

> This is the concrete commit:
https://github.com/RaulBernal/bcnav4wasm/commit/8e41de9b608864e9fefc999985d743d23e5993c4

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned

**Comment by chatton** [comment]
Hi @RaulBernal, it looks like it is now required to set this query router with `ICAHostKeeper.WithQueryRouter`, [here](https://github.com/cosmos/ibc-go/blob/759897bfa401c9fe20f5b27b3be7f384aed7dc54/testing/simapp/app.go#L465) is an example of how to do it from our simapp.

Is it possible for you to add this wiring to your app?

I believe this requirement is due to needing to maintain the go api and not change the method signature of `icahostkeeper.NewKeeper`

This may be a step we missed in the 8.3.1 release notes.

**Comment by RaulBernal** [comment]
Hi @chatton it works! 
```go
12:07PM INF migrating module ibc from version 5 to version 6 module=server
12:07PM INF successfully migrated ibc channel params module=x/ibc/channel
12:07PM INF migrating module interchainaccounts from version 2 to version 3 module=server
12:07PM INF successfully migrated ica/host submodule to self-manage params module=x/ibc-interchainaccounts
12:07PM INF successfully migrated ica/controller submodule to self-manage params module=x/ibc-interchainaccounts
12:07PM INF adding a new module: nft module=server
12:07PM INF adding a new module: runtime module=server
12:07PM INF migrating module slashing from version 3 to version 4 module=server
12:07PM INF migrating module staking from version 4 to version 5 module=server
12:07PM INF migrating module transfer from version 3 to version 4 module=server
12:07PM INF successfully migrated transfer app self-manage params module=x/ibc-transfer
12:07PM INF migrating module transfer from version 4 to version 5 module=server
12:07PM INF successfully added metadata to IBC voucher denominations module=x/ibc-transfer
12:07PM INF adding a new module: wasm module=server
12:07PM INF migrating module auth from version 4 to version 5 module=server
12:07PM INF post migrate version map: map[06-solomachine:0 07-tendermint:0 auth:5 authz:2 bank:4 capability:1 circuit:1 consensus:1 crisis:2 distribution:3 evidence:1 feegrant:2 feeibc:2 genutil:1 gov:5 group:2 ibc:6 interchainaccounts:3 mint:2 nft:1 params:1 runtime:0 slashing:4 staking:5 transfer:5 upgrade:2 vesting:1 wasm:4] module=server
```

Fixed here with your instructions, thanks :)
https://github.com/RaulBernal/bcnav4wasm/commit/f972af8c9bd9a9950cdb5ac59744a3ce080f3112

**Comment by chatton** [comment]
Great to hear it @RaulBernal! Thanks for creating this issue, we'll make sure to update the readmes to include this step.

cc @crodriguezvega

**Comment by chatton** [comment]
Closing this issue as it looks like we do have the docs in the integration section [here](https://ibc.cosmos.network/v8/apps/interchain-accounts/integration.
