### ISSUE TITLE
No concrete type registered for account against interface *types.GenesisAccount

### ISSUE THREAD

**Issue by migueldingli1997** [cosmos/ibc-go#673]
## Summary of Bug

I'm using [Starport](https://github.com/tendermint/starport) with an interchain accounts-enabled chain and ran into an error when Starport tried to run my chain from a genesis export. Running the chain via a good 'ol `binaryd start` exposed the following error:
```
panic: no concrete type registered for type URL /ibc.applications.interchain_accounts.v1.InterchainAccount against interface *types.GenesisAccount
```

Not sure if it means I missed some registration step or the ICA module is missing this registration step?

<details>
  <summary>Here's the full stack trace</summary>
  
```
panic: no concrete type registered for type URL /ibc.applications.interchain_accounts.v1.InterchainAccount against interface *types.GenesisAccount

goroutine 1 [running]:
github.com/cosmos/cosmos-sdk/codec.(*ProtoCodec).MustUnmarshalJSON(0xc0010fcec0, 0xc000dff500, 0xa3e, 0xa80, 0x230b9e0, 0xc000121d00)
        /home/<user>/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.44.5/codec/proto_codec.go:176 +0x98
github.com/cosmos/cosmos-sdk/x/auth.AppModule.InitGenesis(0x2301b90, 0xc000cda480, 0x2334fb8, 0xc0010fcec0, 0x2334fb8, 0xc0010fcec0, 0xc00020cd38, 0x2301b90, 0xc000cda4f0, 0x2301be0, ...)
        /home/<user>/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.44.5/x/auth/module.go:143 +0xa4
github.com/cosmos/cosmos-sdk/types/module.(*Manager).InitGenesis(0xc001140310, 0x231ef48, 0xc00004c0e0, 0x2337d60, 0xc000121340, 0x0, 0x0, 0xc0010e40ea, 0x6, 0x483, ...)
        /home/<user>/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.44.5/types/module/module.go:307 +0x2b5
github.com/myorg/mychain/app.(*App).InitChainer(0xc0010d3b00, 0x231ef48, 0xc00004c0e0, 0x2337d60, 0xc000121340, 0x0, 0x0, 0xc0010e40ea, 0x6, 0x483, ...)
        /home/<user>/mychain/app/app.go:660 +0x170
github.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).InitChain(0xc001232000, 0x256877b5, 0xed960fa23, 0x0, 0xc0010e40ea, 0x6, 0xc0000884c0, 0xc00000e720, 0x1, 0x1, ...)
        /home/<user>/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.44.5/baseapp/abci.go:62 +0x315
github.com/tendermint/tendermint/abci/client.(*localClient).InitChainSync(0xc0011e1740, 0x256877b5, 0xed960fa23, 0x0, 0xc0010e40ea, 0x6, 0xc0000884c0, 0xc00000e720, 0x1, 0x1, ...)
        /home/<user>/go/pkg/mod/github.com/tendermint/tendermint@v0.34.13/abci/client/local_client.go:274 +0x115
github.com/tendermint/tendermint/proxy.(*appConnConsensus).InitChainSync(0xc000202470, 0x256877b5, 0xed960fa23, 0x0, 0xc0010e40ea, 0x6, 0xc0000884c0, 0xc00000e720, 0x1, 0x1, ...)
        /home/<user>/go/pkg/mod/github.com/tendermint/tendermint@v0.34.13/proxy/app_conn.go:77 +0x78
github.com/tendermint/tendermint/consensus.(*Handshaker).ReplayBlocks(0xc000d09c18, 0xb, 0x0, 0x1e6ed00, 0x7, 0xc0010e40ea, 0x6, 0x483, 0x0, 0x0, ...)
        /home/<user>/go/pkg/mod/github.com/tendermint/tendermint@v0.34.13/consensus/replay.go:319 +0x655
github.com/tendermint/tendermint/consensus.(*Handshaker).Handshake(0xc000d09c18, 0x2338e88, 0xc00051b110, 0x1f4, 0xc001315ee0)
        /home/<user>/go/pkg/mod/github.com/tendermint/tendermint@v0.34.13/consensus/replay.go:268 +0x458
github.com/tendermint/tendermint/node.doHandshake(0x2334af8, 0xc00018d6d0, 0xb, 0x0, 0x1e6ed00, 0x7, 0xc0010e40ea, 0x6, 0x483, 0x0, ...)
        /home/<user>/go/pkg/mod/github.com/tendermint/tendermint@v0.34.13/node/node.go:322 +0x1d8
github.com/tendermint/tendermint/node.NewNode(0xc001145400, 0x23165a0, 0xc0001ef680, 0xc00018c9e0, 0x22df4a0, 0xc0012cb968, 0xc00018ca50, 0x20df748, 0xc00018cb40, 0x231fbc0, ...)
        /home/<user>/go/pkg/mod/github.com/tendermint/tendermint@v0.34.13/node/node.go:730 +0x2105
github.com/cosmos/cosmos-sdk/server.startInProcess(0xc001159ee0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x2328bf0, 0xc0010fcec0, ...)
        /home/<user>/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.44.5/server/start.go:263 +0x685
github.com/cosmos/cosmos-sdk/server.StartCmd.func2(0xc001189680, 0xc00125a020, 0x0, 0x2, 0x0, 0x0)
        /home/<user>/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.44.5/server/start.go:129 +0x209
github.com/spf13/cobra.(*Command).execute(0xc001189680, 0xc00125a000, 0x2, 0x2, 0xc001189680, 0xc00125a000)
        /home/<user>/go/pkg/mod/github.com/spf13/cobra@v1.3.0/command.go:856 +0x472
github.com/spf13/cobra.(*Command).ExecuteC(0xc001164000, 0x0, 0x0, 0xc0010ef460)
        /home/<user>/go/pkg/mod/github.com/spf13/cobra@v1.3.0/command.go:974 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
        /home/<user>/go/pkg/mod/github.com/spf13/cobra@v1.3.0/command.go:902
github.com/spf13/cobra.(*Command).ExecuteContext(...)
        /home/<user>/go/pkg/mod/github.com/spf13/cobra@v1.3.0/command.go:895
github.com/cosmos/cosmos-sdk/server/cmd.Execute(0xc001164000, 0xc0010ef460, 0x1a, 0x233ad78, 0xc0010fcec0)
        /home/<user>/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.44.5/server/cmd/execute.go:36 +0x285
main.main()
        /home/<user>/mychain/cmd/mychaind/main.go:13 +0x45
```
</details>

## Version

`v3.0.0-alpha1`

## Steps to Reproduce

- Run chain, register interchain account
- Stop chain, export state to genesis file
- Start chain with export as genesis file

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned

**Comment by colin-axner** [comment]
Hello! Thanks for trying out interchain accounts! Can you point me to your app.go file? Are you using the same binary between exports? 

Which chain is causing this error? The chain which you control the interchain account from or the chain which is hosting the interchain account?

**Comment by damiannolan** [comment]
Hey @colin-axner, I think I have a fix for this. I am just trying to reproduce locally at the moment also.

**Comment by migueldingli1997** [comment]
> Hello! Thanks for trying out interchain accounts! Can you point me to your app.go file? Are you using the same binary between exports?

I cannot point you to the app.go as it is not open source at the moment. But yes I am using the same binary between exports I believe. Possibly re-built by Starport in the background but code unchanged.

> Which chain is causing this error? The chain which you control the interchain account from or the chain which is hosting the interchain account?

I believe the one that is hosting the interchain account but I will confirm.

---

Even though the issue was closed I wish to try to reproduce the error. Will post an update as soon as I do so

**Comment by damiannolan** [comment]
Hi @migueldingli1997, a fix has been merged to main today, however, this is not yet included in a release. It will likely be included in a `v3.0.0-alpha2` pre-release version. 

@colin-axner do you think pointing go.mod to `@latest` would be a good idea, or has there been additional changes wrt. to version negotiation that are not yet accounted for with relayer integration?

**Comment by colin-axner** [comment]
> @colin-axner do you think pointing go.mod to @latest would be a good idea, or has there been additional changes wrt. to version negotiation that are not yet accounted for with relayer integration?

For the interchain accounts demo repo? I think the latest changes should work fine :+1:

**Comment by gjermundgaraba** [comment]
This issue was mistakenly reopened during some integration work, so closing again now.
